### ISSUE TITLE
[Question] Decision on Decodable

### ISSUE THREAD

**Issue by blyscuit** [kothihaaung/nimble-survey-ios#24]
## Issue

What is the decision to use `MP-JSONAPI` instead of just `Decodable` ?

What is the difference between `Poly` and Protocol or Generic? What role is Poly to `MP-JSONAPI`?

**Comment by kothihaaung** [comment]
I used it because it was part of [requirement](https://github.com/nimblehq/nimble-survey-web/wiki/REST-API#ios) and `MP-JSONAPI` is the best client library I could find with rich documentation and examples.
This is my first time usage of JSONAPI. I liked it personally 🙂. Feel more organized and structured.
But still prefer to use pure `Decodable` because of flexibility.
> It's recommended for client applications to either use [a third-party or custom adapter](https://jsonapi.org/implementations/) to deserialize JSON API responses with ease
